# Vagrant
vagrant:
  folders:
    host:
      path: '/var/www'
      nfs: true
    log:
      path: '/var/log/apache2'
      nfs: true

# Guest
guest:
  name: 'Development'
  architecture: '32-bit'
  memory: 1024
  cpus: 1

# Webserver
webserver:
  domain: 'local'
