# Vagrant
vagrant:
  folders:
    host:
      path: '/var/www/host'
  ports:
    80: 80
    443: 443
    3306: 3306

# Guest
guest:
  name: 'Vagrant'
  hostname: 'vagrant'
  memory: 1024
  cpus: 1

# Webserver
webserver:
  domain: 'local'
  environment:
    CONTEXT: 'development'
