# Machine
machine:
  box: 'chef/ubuntu-14.10'
  name: 'Vagrant'
  hostname: 'vagrant'
  memory: 1024
  cpus: 1

# Services
services:
  http: 80
  https: 443
  mysql: 3306
  redis: 6379

# Hosts
hosts:
  directory: '~'

# Environment
environment:
  CONTEXT: 'local'
