# Vagrant
vagrant:
  folders:
    host:
      path: '/var/www/host'
  ports:
    80: 80 # HTTP
    443: 443 # HTTPS
    3306: 3306 # MySQL
    6379: 6379 # Redis

# Guest
guest:
  name: 'Vagrant'
  hostname: 'vagrant'
  memory: 1024
  cpus: 1

# Environment
environment:
  CONTEXT: 'local'
