# Vagrant
vagrant:
  folders:
    dev:
      path: '/var/www/dev'
    host:
      path: '/var/www/host'
  ports:
    80: 80
    443: 443
    3306: 3306

# Guest
guest:
  name: 'Development'
  architecture: '32-bit'
  memory: 1024
  cpus: 1
  hostname: 'vagrant'

# Webserver
webserver:
  domain: 'local'
  environment:
    CONTEXT: 'development'
