# Machine
machine:
  box: 'boxcutter/ubuntu1510'
  version: '>= 2.0'
  name: 'Vagrant'
  hostname: 'vagrant'
  memory: 1024
  cpus: 1
  timezone: 'UTC'

# Services
services:
  http: 80
  https: 443
  mysql: 3306
  redis: 6379
  browser-sync: 3000

# Hosts
webserver:
  engine: 'nginx'
  directory: '~'
  domains:
    - 'local'

# Environment
environment:
  variables:
    - CONTEXT: 'local'

# Mappings
mappings:
  folders:
  ports:
